#Created by Rowan Barr (UNUSED)
version: '3'

networks:
  default_net:
    ipam:
      config:
        - subnet: 172.21.0.0/16
  streaming_network:
    external: true
    driver: bridge
    ipam:
      driver: bridge
      config:
        - subnet: 172.22.0.0/16

services:
    producer:
      container_name: producer
      image: stream_network
      working_dir: /work_space/Producer
      stdin_open: true  # Keep stdin open
      tty: true        # Allocate a pseudo-TTY for bash
      cap_add:
        - ALL
      networks:
        default_net:
        streaming_network:
          ipv4_address: 172.22.0.2

    broker:
      container_name: broker
      image: stream_network
      working_dir: /work_space/Broker
      stdin_open: true  # Keep stdin open
      tty: true        # Allocate a pseudo-TTY for bash
      cap_add:
        - ALL
      networks:
        default_net:
        streaming_network:
          ipv4_address: 172.22.0.3


    consumer:
      container_name: consumer
      image: stream_network
      working_dir: /work_space/Consumer
      stdin_open: true  # Keep stdin open
      tty: true        # Allocate a pseudo-TTY for bash
      cap_add:
        - ALL
      networks:
        default_net:
        streaming_network:
          ipv4_address: 172.22.0.4


