//
// Created by rowan on 01/10/2023.
//

#ifndef STREAM_NETWORK_PROTOCOL_CONSTANTS_H
#define STREAM_NETWORK_PROTOCOL_CONSTANTS_H

const unsigned char CONTROL_REQUEST_CONNECT = 0b10000011;

#endif //STREAM_NETWORK_PROTOCOL_CONSTANTS_H
