//
// Created by rowan on 01/10/2023.
//

#ifndef STREAM_NETWORK_PROTOCOL_CONSTANTS_H
#define STREAM_NETWORK_PROTOCOL_CONSTANTS_H

#define MAX_CLIENTS 32
#define MAX_PRODUCERS 32


const unsigned char CONTROL_PROD_REQUEST_CONNECT = 0b10001001;
const unsigned char CONTROL_VIDEO_FRAME = 0b00010000;
const unsigned char CONTROL_TEXT_FRAME = 0b01000000;

#endif //STREAM_NETWORK_PROTOCOL_CONSTANTS_H
